apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.fullnameOverride }}
spec:
  entryPoints:
    - web
  routes:
    - match: (Host(`{{ .Values.route.host }}`) && Path(`{{ .Values.route.path }}`))
      kind: Rule
      services:
        - name: {{ .Values.fullnameOverride }}
          port: {{ .Values.route.port }}
          kind: Service