apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.fullname" . }}-loadbalancer
  namespace: {{ include "mysql.fullname" . }}
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: {{ .Values.service.clusterIP }}
  clusterIPs:
    - {{ .Values.service.clusterIP }}
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: {{ include "mysql.fullname" . }}
      nodePort: 30213
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "mysql.labels" . | nindent 4 }}
  sessionAffinity: None
  type: LoadBalancer