#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: mysql
#spec:
#  capacity:
#    storage: 8Gi
#  volumeMode: Filesystem
#  accessModes:
#    - ReadWriteOnce
##  persistentVolumeReclaimPolicy: Delete
#  storageClassName: longhorn
#  csi:
#    driver: driver.longhorn.io
#    fsType: ext4
#    volumeAttributes:
#      numberOfReplicas: '3'
#      staleReplicaTimeout: '2880'
#    volumeHandle: existing-longhorn-volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi