apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mysql.fullname" . }}
  namespace: {{ include "mysql.fullname" . }}
spec:
  selector:
    matchLabels:
        {{- include "hello-world.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hello-world.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              value: adminpass
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ include "mysql.fullname" . }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: {{ include "mysql.fullname" . }}
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/{{ include "mysql.fullname" . }}
              name: {{ include "mysql.fullname" . }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /home/ubuntu/{{ include "mysql.fullname" . }}-data
            type: ''
          name: {{ include "mysql.fullname" . }}
  podManagementPolicy: OrderedReady
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  serviceName: {{ include "mysql.fullname" . }}
  updateStrategy:
    type: OnDelete