replicaCount: 1

image:
  repository: ksdn117/lorem-ipsum
  pullPolicy: Always

imagePullSecrets: []
nameOverride: "hello-world"
fullnameOverride: "hello-world"

service:
  type: ClusterIP
  port: 80

container:
  port: 80

route:
  host: kuberstar.com
  path: /
  port: 80

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
