replicaCount: 1

image:
  repository: nginx
  pullPolicy: Always
  tag: ""

imagePullSecrets: []
nameOverride: "nginx"
fullnameOverride: "nginx"

service:
  type: ClusterIP
  port: 80

container:
  port: 80

route:
  host: kuberstar.com
  path: /
  port: 80

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
