replicaCount: 1

image:
  repository: arm64v8/mysql
  pullPolicy: IfNotPresent

nameOverride: "mysql"
fullnameOverride: "mysql"

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  clusterIP: 10.43.79.175