replicaCount: 1

image:
  repository: registry.kuberstar.com/telegram/bot
  pullPolicy: Always
  imagePullSecrets: kuberstar-registry

nameOverride: "bot"
fullnameOverride: "bot"
namespace: "kuberstar"

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

container:
  port: 3000

route:
  host: kuberstar.com

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80