apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "duplicati.fullname" . }}
  labels:
    {{- include "duplicati.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "duplicati.selectorLabels" . | nindent 6 }}
  template:
    metadata:
        {{- with .Values.podAnnotations }}
      annotations:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
          {{- include "duplicati.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "duplicati.fullname" . }}
          env:
            - { name: PUID, value: "0" }
            - { name: TZ, value: $TZ }
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: {{ .Values.container.port }}
              protocol: TCP
          volumeMounts:
            - mountPath: /source/myqsl
              name: mysql
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - name: mysql
          hostPath: { path: /home/ubuntu/mysql_home }
  podManagementPolicy: OrderedReady
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  serviceName: {{ include "duplicati.fullname" . }}
  updateStrategy:
    type: OnDelete