apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.fullname" . }}-loadbalancer
  namespace: {{ include "mysql.fullname" . }}
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":["172.16.0.153"],"port":3306,"protocol":"TCP","serviceName":"mysql:mysql-loadbalancer","allNodes":false}]'
    field.cattle.io/targetWorkloadIds: '["mysql/mysql"]'
    management.cattle.io/ui-managed: "true"
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: {{ .Values.service.clusterIP }}
  clusterIPs:
    - {{ .Values.service.clusterIP }}
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: {{ include "mysql.fullname" . }}
      nodePort: 30213
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
  selector:
    workload.user.cattle.io/workloadselector: apps.statefulset-mysql-mysql
  sessionAffinity: None
  type: LoadBalancer